### ISSUE TITLE
project{,-bare} archetype: repos

### ISSUE THREAD

**Issue by maggu2810** [osgi/osgi.enroute#88]
The POM file that is generated by the archetype `project` and `project-bare` adds two repositories and one plugin repository (and one of each also for snapshots):

```xml
<repositories>
    <repository>
        <id>OSGi</id>
        <name>OSGi public binaries</name>
        <url>https://oss.sonatype.org/content/groups/osgi</url>
        <releases>
            <enabled>true</enabled>
        </releases>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
    <repository>
        <id>Apache Snapshots</id>
        <url>https://repository.apache.org/content/groups/snapshots/</url>
        <releases>
            <enabled>false</enabled>
        </releases>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
</repositories>

<pluginRepositories>
    <pluginRepository>
        <id>Bnd Snapshots</id>
        <name>Bnd Latest build</name>
        <url>https://bndtools.ci.cloudbees.com/job/bnd.master/lastSuccessfulBuild/artifact/dist/bundles/</url>
        <releases>
            <enabled>false</enabled>
        </releases>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </pluginRepository>
</pluginRepositories>
```

Wouldn't it make sense to remove that part in front of a release and keep it on development of this repository only?
It will be part of the POMs generated by the 7.0.0 archetype but there is no need as all artifacts (AFAIK) can be resolved by Maven Central.

**Comment by timothyjward** [comment]
It is true that these repositories could be removed, however they do also provide a way for users to quickly and easily try out new versions of specifications and tools. Obviously users should not try to release their code when depending on snapshots, but Maven will prevent that anyway. The existing model is therefore intended to favour ease of use.

For example the Bnd 4.1.0 release is known to have a couple of bugs in its handling of R7 annotations. These are fixed in the 4.2.0-SNAPSHOT, but not otherwise available. Similarly there are numerous Apache projects which release SNAPSHOT builds allowing users to try out fixes by depending on the component.

I am open to a discussion about changing the current policy, but hopefully this helps to explain why it is the way it is.
